In [1]:
from Bio import SeqIO
import pandas as pd
import numpy as np
from pathlib import Path
import openpyxl

In [2]:
mouse_fasta_path = "./fasta_files/radus_database__cravattlab_mouse_nonredundant_07-11-2017_reversed.fasta"

In [3]:
fasta_dict = {}
with open(mouse_fasta_path) as handle:
    for record in SeqIO.parse(handle, "fasta"):
        fasta_dict[record.id] = record.description

In [4]:
df = pd.DataFrame.from_dict(fasta_dict, orient='index')

In [5]:
df = df.reset_index()

In [6]:
df.columns = ["uniprot_id", "description"]

In [7]:
df["id"] = df["uniprot_id"]

In [8]:
df.head()

,uniprot_id,description,id
0,tr|A0A075B645|A0A075B645_MOUSE,tr|A0A075B645|A0A075B645_MOUSE Trav14n-3 Prote...,tr|A0A075B645|A0A075B645_MOUSE
1,sp|Q9CQW2|ARL8B_MOUSE,sp|Q9CQW2|ARL8B_MOUSE Arl8b ADP-ribosylation f...,sp|Q9CQW2|ARL8B_MOUSE
2,tr|Q5RKT9|Q5RKT9_MOUSE,"tr|Q5RKT9|Q5RKT9_MOUSE Mgat3 Beta-1,4-mannosyl...",tr|Q5RKT9|Q5RKT9_MOUSE
3,sp|Q6ZWR6|SYNE1_MOUSE,sp|Q6ZWR6|SYNE1_MOUSE Syne1 Nesprin-1 [REVIEWE...,sp|Q6ZWR6|SYNE1_MOUSE
4,sp|Q9CQK8|SPR2A_MOUSE,sp|Q9CQK8|SPR2A_MOUSE Sprr2a Small proline-ric...,sp|Q9CQK8|SPR2A_MOUSE

In [9]:
df[["db","uniprot_id","entry_name"]] = df["uniprot_id"].str.split("|", expand=True)

In [11]:
df.head()

,uniprot_id,description,id,db,entry_name
0,A0A075B645,tr|A0A075B645|A0A075B645_MOUSE Trav14n-3 Prote...,tr|A0A075B645|A0A075B645_MOUSE,tr,A0A075B645_MOUSE
1,Q9CQW2,sp|Q9CQW2|ARL8B_MOUSE Arl8b ADP-ribosylation f...,sp|Q9CQW2|ARL8B_MOUSE,sp,ARL8B_MOUSE
2,Q5RKT9,"tr|Q5RKT9|Q5RKT9_MOUSE Mgat3 Beta-1,4-mannosyl...",tr|Q5RKT9|Q5RKT9_MOUSE,tr,Q5RKT9_MOUSE
3,Q6ZWR6,sp|Q6ZWR6|SYNE1_MOUSE Syne1 Nesprin-1 [REVIEWE...,sp|Q6ZWR6|SYNE1_MOUSE,sp,SYNE1_MOUSE
4,Q9CQK8,sp|Q9CQK8|SPR2A_MOUSE Sprr2a Small proline-ric...,sp|Q9CQK8|SPR2A_MOUSE,sp,SPR2A_MOUSE

In [12]:
df["reverse"] = df["id"].str.contains("Reverse_")

In [13]:
df.shape

(43302, 6)

In [14]:
df = df[df["reverse"] == False]

In [15]:
master_table = df.drop("reverse", axis=1)

In [16]:
master_table.shape

(21651, 5)

In [17]:
master_table.set_index("id", inplace=True)

In [162]:
master_table.to_csv("from_fasta_to_mouse_master_table.csv") #run uniprot ID mapping with this file

In [18]:
#import uniprot id mapping results 
uniprot_id_mapping_path = "./fasta_files/uniprot_id_mapping/mouse_mapping_uniprot-download_true_fields_accession_2Creviewed_2Cid_2Cprotein_nam-2022.08.31-15.17.09.71.csv"

In [19]:
uniprot_mapping = pd.read_csv(uniprot_id_mapping_path)

In [20]:
uniprot_mapping.shape

(21407, 18)

In [21]:
uniprot_mapping["keratin"] = uniprot_mapping["Protein names"].str.contains("keratin", case=False)

In [22]:
uniprot_mapping.rename({"From":"uniprot_id"}, axis=1, inplace=True)

In [23]:
uniprot_mapping.head()

,uniprot_id,Entry,Reviewed,Entry Name,Protein names,Gene Names,Organism,Length,Gene Ontology (biological process),Gene Ontology (GO),Gene Ontology IDs,Gene Ontology (cellular component),Gene Ontology (molecular function),Subcellular location [CC],Protein families,Signal peptide,Zinc finger,Mass,keratin
0,A0A075B645,A0A075B645,unreviewed,A0A075B645_MOUSE,T cell receptor alpha variable 14N-3,Trav14n-3 Trav14-1,Mus musculus (Mouse),120,NaN,peptide antigen binding [GO:0042605],GO:0042605,NaN,peptide antigen binding [GO:0042605],NaN,NaN,"SIGNAL 1..21; /evidence=""ECO:0000256|SAM:SignalP""",NaN,13520,False
1,Q9CQW2,Q9CQW2,reviewed,ARL8B_MOUSE,"ADP-ribosylation factor-like protein 8B, EC 3....",Arl8b Arl10c Gie1,Mus musculus (Mouse),186,anterograde axonal transport [GO:0008089]; ant...,anchoring junction [GO:0070161]; axon [GO:0030...,GO:0001778; GO:0002505; GO:0002747; GO:0003925...,anchoring junction [GO:0070161]; axon [GO:0030...,alpha-tubulin binding [GO:0043014]; beta-tubul...,SUBCELLULAR LOCATION: Late endosome membrane {...,"Small GTPase superfamily, Arf family",NaN,NaN,21539,False
2,Q5RKT9,Q5RKT9,unreviewed,Q5RKT9_MOUSE,"Beta-1,4-mannosyl-glycoprotein 4-beta-N-acetyl...",Mgat3,Mus musculus (Mouse),538,protein localization [GO:0008104]; protein N-l...,"membrane [GO:0016020]; beta-1,4-mannosylglycop...",GO:0003830; GO:0006487; GO:0008104; GO:0016020...,membrane [GO:0016020],"beta-1,4-mannosylglycoprotein 4-beta-N-acetylg...",NaN,NaN,NaN,NaN,62051,False
3,Q6ZWR6,Q6ZWR6,reviewed,SYNE1_MOUSE,Nesprin-1 (Enaptin) (KASH domain-containing pr...,Syne1,Mus musculus (Mouse),8799,centrosome localization [GO:0051642]; Golgi or...,cytoplasm [GO:0005737]; cytoskeleton [GO:00058...,GO:0000932; GO:0003779; GO:0005521; GO:0005635...,cytoplasm [GO:0005737]; cytoskeleton [GO:00058...,actin binding [GO:0003779]; actin filament bin...,SUBCELLULAR LOCATION: Nucleus outer membrane {...,Nesprin family,NaN,NaN,1009926,False
4,Q9CQK8,Q9CQK8,reviewed,SP2A1_MOUSE,Small proline-rich protein 2A1 (small proline-...,Sprr2a1 Sprr2a,Mus musculus (Mouse),83,antibacterial humoral response [GO:0019731]; d...,cornified envelope [GO:0001533]; cytoplasm [GO...,GO:0001533; GO:0005200; GO:0005576; GO:0005615...,cornified envelope [GO:0001533]; cytoplasm [GO...,lipid binding [GO:0008289]; structural constit...,SUBCELLULAR LOCATION: Secreted {ECO:0000269|Pu...,Cornifin (SPRR) family,NaN,NaN,9408,False

In [24]:
#merge with master table
merged_master = master_table.merge(uniprot_mapping, on="uniprot_id", how="outer")

In [25]:
merged_master.head()

,uniprot_id,description,db,entry_name,Entry,Reviewed,Entry Name,Protein names,Gene Names,Organism,...,Gene Ontology (GO),Gene Ontology IDs,Gene Ontology (cellular component),Gene Ontology (molecular function),Subcellular location [CC],Protein families,Signal peptide,Zinc finger,Mass,keratin
0,A0A075B645,tr|A0A075B645|A0A075B645_MOUSE Trav14n-3 Prote...,tr,A0A075B645_MOUSE,A0A075B645,unreviewed,A0A075B645_MOUSE,T cell receptor alpha variable 14N-3,Trav14n-3 Trav14-1,Mus musculus (Mouse),...,peptide antigen binding [GO:0042605],GO:0042605,NaN,peptide antigen binding [GO:0042605],NaN,NaN,"SIGNAL 1..21; /evidence=""ECO:0000256|SAM:SignalP""",NaN,13520.0,False
1,Q9CQW2,sp|Q9CQW2|ARL8B_MOUSE Arl8b ADP-ribosylation f...,sp,ARL8B_MOUSE,Q9CQW2,reviewed,ARL8B_MOUSE,"ADP-ribosylation factor-like protein 8B, EC 3....",Arl8b Arl10c Gie1,Mus musculus (Mouse),...,anchoring junction [GO:0070161]; axon [GO:0030...,GO:0001778; GO:0002505; GO:0002747; GO:0003925...,anchoring junction [GO:0070161]; axon [GO:0030...,alpha-tubulin binding [GO:0043014]; beta-tubul...,SUBCELLULAR LOCATION: Late endosome membrane {...,"Small GTPase superfamily, Arf family",NaN,NaN,21539.0,False
2,Q5RKT9,"tr|Q5RKT9|Q5RKT9_MOUSE Mgat3 Beta-1,4-mannosyl...",tr,Q5RKT9_MOUSE,Q5RKT9,unreviewed,Q5RKT9_MOUSE,"Beta-1,4-mannosyl-glycoprotein 4-beta-N-acetyl...",Mgat3,Mus musculus (Mouse),...,"membrane [GO:0016020]; beta-1,4-mannosylglycop...",GO:0003830; GO:0006487; GO:0008104; GO:0016020...,membrane [GO:0016020],"beta-1,4-mannosylglycoprotein 4-beta-N-acetylg...",NaN,NaN,NaN,NaN,62051.0,False
3,Q6ZWR6,sp|Q6ZWR6|SYNE1_MOUSE Syne1 Nesprin-1 [REVIEWE...,sp,SYNE1_MOUSE,Q6ZWR6,reviewed,SYNE1_MOUSE,Nesprin-1 (Enaptin) (KASH domain-containing pr...,Syne1,Mus musculus (Mouse),...,cytoplasm [GO:0005737]; cytoskeleton [GO:00058...,GO:0000932; GO:0003779; GO:0005521; GO:0005635...,cytoplasm [GO:0005737]; cytoskeleton [GO:00058...,actin binding [GO:0003779]; actin filament bin...,SUBCELLULAR LOCATION: Nucleus outer membrane {...,Nesprin family,NaN,NaN,1009926.0,False
4,Q9CQK8,sp|Q9CQK8|SPR2A_MOUSE Sprr2a Small proline-ric...,sp,SPR2A_MOUSE,Q9CQK8,reviewed,SP2A1_MOUSE,Small proline-rich protein 2A1 (small proline-...,Sprr2a1 Sprr2a,Mus musculus (Mouse),...,cornified envelope [GO:0001533]; cytoplasm [GO...,GO:0001533; GO:0005200; GO:0005576; GO:0005615...,cornified envelope [GO:0001533]; cytoplasm [GO...,lipid binding [GO:0008289]; structural constit...,SUBCELLULAR LOCATION: Secreted {ECO:0000269|Pu...,Cornifin (SPRR) family,NaN,NaN,9408.0,False

In [171]:
#merged_master.to_csv("from_fasta_to_mouse_master_table_with_uniprot_mapping.csv")

In [41]:
merged_master["Subcellular location [CC]"].str.contains("Mitochondrion")

0          NaN
1        False
2          NaN
3        False
4        False
         ...
21654    False
21655      NaN
21656    False
21657      NaN
21658    False
Name: Subcellular location [CC], Length: 21659, dtype: object

In [42]:
def annotate_TP(subcelullar_location):
    tp_term_list = ["Endoplasmic Reticulum", "Secreted", "secreted", "Endoplasmic reticulum", "Rough endoplasmic reticulum", "endoplasmic reticulum"]
    #"Golgi", "Extracellular space", "extracellular space", 
    #
    subcelullar_location = str(subcelullar_location)
    if "Note:" in subcelullar_location:
        subcelullar_location = subcelullar_location.split("Note:")[0]
    for item in tp_term_list: 
        if item in subcelullar_location:
            return("TP")
    
def annotate_FP(subcelullar_location):
    fp_term_list = ["Nucleus", "nucleus", "Mitochondrion", "mitochondrion"] #'cytoskeleton' "Cytoskeleton", 
    subcelullar_location = str(subcelullar_location)
    if "Note:" in subcelullar_location:
        subcelullar_location = subcelullar_location.split("Note:")[0]
    for item in fp_term_list: 
        if item in subcelullar_location:
            return("FP")

In [43]:
#TP
merged_master["TP"] = merged_master["Subcellular location [CC]"].apply(annotate_TP) 
merged_master["FP"] = merged_master["Subcellular location [CC]"].apply(annotate_FP) #chnage to cyt_nuc if you add Transcirption factors

In [44]:
merged_master.shape

(21659, 24)

In [45]:
merged_master["TP"].value_counts()

TP    2808
Name: TP, dtype: int64

In [46]:
merged_master["FP"].value_counts()

FP    5710
Name: FP, dtype: int64

In [47]:
#add Transcription factor as FP
#mouse_tfs_df = pd.read_csv("/Users/nropek/Documents/01_data_analysis_folders/05_TurboID/uniprot_noteboook/combine_uniprot_IDs_per_species/mouse/01_cyt_nuc_TFs/mouse_proteome_TFs.csv", index_col=0)
#mouse_tfs_df["TFs"] = "FP"
#mouse_tfs_df = mouse_tfs_df[["Entry", "TFs"]]

In [48]:
#mouse_tfs_df

In [49]:
#merged_master = merged_master.merge(mouse_tfs_df, on=["Entry"], how="left")

In [50]:
merged_master.columns

Index(['uniprot_id', 'description', 'db', 'entry_name', 'Entry', 'Reviewed',
       'Entry Name', 'Protein names', 'Gene Names', 'Organism', 'Length',
       'Gene Ontology (biological process)', 'Gene Ontology (GO)',
       'Gene Ontology IDs', 'Gene Ontology (cellular component)',
       'Gene Ontology (molecular function)', 'Subcellular location [CC]',
       'Protein families', 'Signal peptide', 'Zinc finger', 'Mass', 'keratin',
       'TP', 'FP'],
      dtype='object')

In [51]:
#merged_master.value_counts("TFs")

In [52]:
merged_master["Signal peptide"].notna().sum()

3915

In [53]:
merged_master["Signal peptide"].isnull().sum()

17744

In [54]:
def annotation(df):   
    #if df["TP"] == "TP" and pd.notna(df["Signal peptide"]):
    #    return(np.nan)
    #elif df["TP"] == "TP" and pd.isnull(df["Signal peptide"]):
    #    return("TP")
    
    if df["TP"] == "TP":
        return("TP")
    #elif df["FP"] == "FP":
    #    return("FP")
    elif df["FP"] == "FP" and pd.notna(df["Signal peptide"]):
        return(np.nan)
    elif df["FP"] == "FP" and pd.isnull(df["Signal peptide"]):
        return("FP")

In [55]:
merged_master["annotation"] = merged_master.apply(annotation, axis=1)

In [56]:
merged_master["annotation"].value_counts()

FP    5344
TP    2808
Name: annotation, dtype: int64

In [57]:
#merged_master.to_csv("mouse_master_table_with_annotation.csv")

In [58]:
#check how many with Signal P are marked as TP or FP
merged_master[merged_master["annotation"]=="FP"]["Signal peptide"].notna().sum() #value_counts().sum()

0

In [59]:
merged_master[merged_master["annotation"]=="TP"]["Signal peptide"].value_counts().sum()

1737

In [60]:
#crossreference master list with spleen, adipose tissue etc.
tissue_localisation_path = "/Users/nropek/Dropbox (Dropbox @RU)/TurboID manuscript/Reference datasets/Mouse/Tissue localisation"
tissue_localisation_path_obj = Path(tissue_localisation_path)

In [61]:
files_in_folder = list(tissue_localisation_path_obj.iterdir())
files_in_folder

[PosixPath('/Users/nropek/Dropbox (Dropbox @RU)/TurboID manuscript/Reference datasets/Mouse/Tissue localisation/liver_from_hpa_to_mouse_uniprot-download_true_fields_accession_2Creviewed_2Cid_2Cprotein_nam-2022.10.28-19.30.39.96.xlsx'),
 PosixPath('/Users/nropek/Dropbox (Dropbox @RU)/TurboID manuscript/Reference datasets/Mouse/Tissue localisation/normal-tissue_all_HPA_to_mouse_uniprot-download_true_fields_accession_2Creviewed_2Cid_2Cprotein_nam-2022.10.28-18.58.57.91.xlsx'),
 PosixPath('/Users/nropek/Dropbox (Dropbox @RU)/TurboID manuscript/Reference datasets/Mouse/Tissue localisation/adipose-tissue_adipocytes_from_HPA_uniprot-download_true_fields_accession_2Creviewed_2Cid_2Cprotein_nam-2022.10.28-19.05.15.17.xlsx'),
 PosixPath('/Users/nropek/Dropbox (Dropbox @RU)/TurboID manuscript/Reference datasets/Mouse/Tissue localisation/spleen-white-pulp_from_hpa_to_mouse_uniprot-download_true_fields_accession_2Creviewed_2Cid_2Cprotein_nam-2022.10.28-18.46.32.67.xlsx')]

In [62]:
for file_path in files_in_folder:
    column_name = file_path.stem.split("_", 1)[0]
    df = pd.read_excel(file_path, engine='openpyxl')
    entry_list = df.Entry.tolist()
    merged_master[column_name] = merged_master.uniprot_id.isin(entry_list)

/opt/miniconda3/envs/uniprot_notebook/lib/python3.10/site-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/opt/miniconda3/envs/uniprot_notebook/lib/python3.10/site-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/opt/miniconda3/envs/uniprot_notebook/lib/python3.10/site-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/opt/miniconda3/envs/uniprot_notebook/lib/python3.10/site-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [63]:
merged_master.columns

Index(['uniprot_id', 'description', 'db', 'entry_name', 'Entry', 'Reviewed',
       'Entry Name', 'Protein names', 'Gene Names', 'Organism', 'Length',
       'Gene Ontology (biological process)', 'Gene Ontology (GO)',
       'Gene Ontology IDs', 'Gene Ontology (cellular component)',
       'Gene Ontology (molecular function)', 'Subcellular location [CC]',
       'Protein families', 'Signal peptide', 'Zinc finger', 'Mass', 'keratin',
       'TP', 'FP', 'annotation', 'liver', 'normal-tissue', 'adipose-tissue',
       'spleen-white-pulp'],
      dtype='object')

In [64]:
len(merged_master)

21659

In [65]:
merged_master.to_csv("withmitoinFP_reducedTP_mouse_master_table_for_ROC_analysis.csv")