In [3]:
import pandas as pd

In [14]:
biomart_results_df = pd.read_csv("biomart_results.csv")
gene_list_df = pd.read_csv("TFs.csv")
#gene_list = gene_list_df["TFs (GSEA, 2022)"].tolist()
#len(gene_list)

#for item in gene_list:
#    print(item+", ")

biomart_results_df
gene_list_df

     TFs (GSEA, 2022)
0                AATF
1                ABT1
2              ACVR2A
3                ADNP
4               ADNP2
...               ...
1531           ZNF672
1532           ZNF706
1533           ZNF708
1534           ZNF746
1535           ZNF875

[1536 rows x 1 columns]

In [15]:
biomart_results_df = biomart_results_df.dropna()
biomart_results_df.columns = ["Uniprot ID", "TFs (GSEA, 2022)"]

In [20]:
new_df = pd.merge(gene_list_df, biomart_results_df, on="TFs (GSEA, 2022)", how="left")

In [21]:
#new_df.to_csv("new_df.csv")

In [155]:
manual_results_df = pd.read_csv("biomart_uniprot_manual.csv")

In [156]:
manual_results_df
list_manual_results = manual_results_df["gene_name"].tolist()

In [157]:
uniprot_table = pd.read_csv("uniprot_table.csv")
uniprot_table.columns
uniprot_table.shape

(1481, 13)

In [1]:
def check_if_contains(gene_names):
    list_gene_names = gene_names.split()
    #list_gene_names = list_gene_names
    result_list = []
    for name in list_gene_names:
        if name in list_manual_results:
            result_list.append(name)
    return("".join(result_list))

In [2]:
uniprot_table["TFs (GSEA, 2022)"] = uniprot_table["Gene Names"].apply(check_if_contains)
#uniprot_table[["Gene Names", "TFs (GSEA, 2022)"]]

NameError: name 'uniprot_table' is not defined

In [160]:
uniprot_table.shape

(1481, 14)

In [161]:
manual_results_df.columns = ['TFs (GSEA, 2022)', 'uniprot_id', 'note']

In [162]:
uniprot_table = pd.merge(uniprot_table, manual_results_df, on="TFs (GSEA, 2022)", how="left")
uniprot_table = uniprot_table.drop_duplicates()
uniprot_table

,From,Entry,Reviewed,Entry Name,Protein names,Gene Names,Organism,Length,Gene Ontology (biological process),Gene Ontology (GO),Gene Ontology IDs,Gene Ontology (cellular component),Gene Ontology (molecular function),"TFs (GSEA, 2022)",uniprot_id,note
0,A0A1W2PPF3,A0A1W2PPF3,reviewed,DUXB_HUMAN,Double homeobox protein B,DUXB,Homo sapiens (Human),345,regulation of transcription by RNA polymerase ...,nucleus [GO:0005634]; DNA-binding transcriptio...,GO:0000977; GO:0000981; GO:0005634; GO:0006357,nucleus [GO:0005634],"DNA-binding transcription factor activity, RNA...",DUXB,A0A1W2PPF3,NaN
1,A2RU54,A2RU54,reviewed,HMX2_HUMAN,Homeobox protein HMX2 (Homeobox protein H6 fam...,HMX2,Homo sapiens (Human),273,brain development [GO:0007420]; cell different...,chromatin [GO:0000785]; nucleus [GO:0005634]; ...,GO:0000785; GO:0000977; GO:0000981; GO:0005634...,chromatin [GO:0000785]; nucleus [GO:0005634],"DNA-binding transcription factor activity, RNA...",HMX2,A2RU54,NaN
2,A6NCS4,A6NCS4,reviewed,NKX26_HUMAN,Homeobox protein Nkx-2.6 (Homeobox protein NK-...,NKX2-6 NKX2F,Homo sapiens (Human),301,atrial cardiac muscle cell development [GO:005...,chromatin [GO:0000785]; nucleus [GO:0005634]; ...,GO:0000785; GO:0000978; GO:0000981; GO:0001228...,chromatin [GO:0000785]; nucleus [GO:0005634],"DNA-binding transcription activator activity, ...",NKX2-6,A6NCS4,NaN
3,A6NDR6,A6NDR6,reviewed,ME3L1_HUMAN,Putative homeobox protein Meis3-like 1,MEIS3P1,Homo sapiens (Human),274,animal organ morphogenesis [GO:0009887]; brain...,nucleus [GO:0005634]; DNA-binding transcriptio...,GO:0000978; GO:0000981; GO:0001228; GO:0001654...,nucleus [GO:0005634],"DNA-binding transcription activator activity, ...",MEIS3P1,A6NDR6,manual check: found
4,A6NFQ7,A6NFQ7,reviewed,DPRX_HUMAN,Divergent paired-related homeobox,DPRX,Homo sapiens (Human),191,regulation of transcription by RNA polymerase ...,chromatin [GO:0000785]; nucleus [GO:0005634]; ...,GO:0000785; GO:0000978; GO:0000981; GO:0005634...,chromatin [GO:0000785]; nucleus [GO:0005634],"DNA-binding transcription factor activity, RNA...",DPRX,A6NFQ7,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1485,Q9Y6Q3,Q9Y6Q3,reviewed,ZFP37_HUMAN,"Zinc finger protein 37 homolog, Zfp-37",ZFP37,Homo sapiens (Human),630,negative regulation of transcription by RNA po...,nucleus [GO:0005634]; DNA-binding transcriptio...,GO:0000122; GO:0000977; GO:0000981; GO:0001227...,nucleus [GO:0005634],DNA-binding transcription factor activity [GO:...,ZFP37,Q9Y6Q3,NaN
1486,Q9Y6Q9,Q9Y6Q9,reviewed,NCOA3_HUMAN,"Nuclear receptor coactivator 3, NCoA-3, EC 2.3...",NCOA3 AIB1 BHLHE42 RAC3 TRAM1,Homo sapiens (Human),1424,cell dedifferentiation [GO:0043697]; cellular ...,chromatin [GO:0000785]; cytoplasm [GO:0005737]...,GO:0000785; GO:0000993; GO:0003713; GO:0004402...,chromatin [GO:0000785]; cytoplasm [GO:0005737]...,disordered domain specific binding [GO:0097718...,NCOA3,Q9Y6Q9,NaN
1487,Q9Y6X0,Q9Y6X0,reviewed,SETBP_HUMAN,"SET-binding protein, SEB",SETBP1 KIAA0437,Homo sapiens (Human),1596,histone H3-K36 dimethylation [GO:0097676]; his...,cytosol [GO:0005829]; nuclear body [GO:0016604...,GO:0003677; GO:0005654; GO:0005829; GO:0006355...,cytosol [GO:0005829]; nuclear body [GO:0016604...,DNA binding [GO:0003677]; histone methyltransf...,SETBP1,Q9Y6X0,NaN
1488,Q9Y6X2,Q9Y6X2,reviewed,PIAS3_HUMAN,"E3 SUMO-protein ligase PIAS3, EC 2.3.2.- (E3 S...",PIAS3,Homo sapiens (Human),628,negative regulation of gene expression [GO:001...,cytoplasm [GO:0005737]; dendrite [GO:0030425];...,GO:0000122; GO:0003712; GO:0005654; GO:0005737...,cytoplasm [GO:0005737]; dendrite [GO:0030425];...,enzyme binding [GO:0019899]; potassium channel...,PIAS3,Q9Y6X2,NaN
1489,Q9Y6X8,Q9Y6X8,reviewed,ZHX2_HUMAN,Zinc fingers and homeoboxes protein 2 (Alpha-f...,ZHX2 AFR1 KIAA0854 RAF,Homo sapiens (Human),837,mRNA catabolic process [GO:0006402]; negative ...,chromatin [GO:0000785]; cytosol [GO:0005829]; ...,GO:0000122; GO:0000785; GO:0000981; GO:0003677...,chromatin [GO:0000785]; cytosol [GO:0005829]; ...,DNA binding [GO:0003677]; DNA-binding transcri...,ZHX2,Q9Y6X8,NaN

In [90]:
#uniprot_table.to_csv("uniprot_mapping_human.csv")

In [154]:
uniprot_mapping_human_1551 = pd.read_csv("uniprot_mapping_human_1551.csv")
gene_list_df = pd.read_csv("TFs.csv")
uniprot_mapping_human_1551.shape

(1550, 15)

In [97]:
uniprot_mapping_human_1551.columns

Index(['From', 'Entry', 'Reviewed', 'Entry Name', 'Protein names',
       'Gene Names', 'Organism', 'Length',
       'Gene Ontology (biological process)', 'Gene Ontology (GO)',
       'Gene Ontology IDs', 'Gene Ontology (cellular component)',
       'Gene Ontology (molecular function)', 'TFs (GSEA, 2022)', 'NOTE'],
      dtype='object')

In [98]:
gene_list_df.columns

Index(['TFs (GSEA, 2022)', 'placeholder'], dtype='object')

In [113]:
new_uniprot_table = pd.merge(uniprot_mapping_human_1551, gene_list_df, on="TFs (GSEA, 2022)", how="outer")

In [102]:
#new_uniprot_table.to_csv("new_uniprot_table_02.csv")

In [114]:
#new_uniprot_table = new_uniprot_table.drop_duplicates()
new_uniprot_table[new_uniprot_table.duplicated(keep=False)]

,From,Entry,Reviewed,Entry Name,Protein names,Gene Names,Organism,Length,Gene Ontology (biological process),Gene Ontology (GO),Gene Ontology IDs,Gene Ontology (cellular component),Gene Ontology (molecular function),"TFs (GSEA, 2022)",NOTE,placeholder
97,L0R8F8,L0R8F8,reviewed,MIDUO_HUMAN,MIEF1 upstream open reading frame protein (Alt...,MIEF1,Homo sapiens (Human),70.0,cellular response to hypoxia [GO:0071456]; pos...,mitochondrial matrix [GO:0005759]; mitochondri...,GO:0005739; GO:0005759; GO:0042254; GO:0070131...,mitochondrial matrix [GO:0005759]; mitochondri...,NaN,MIEF1,NaN,x
98,L0R8F8,L0R8F8,reviewed,MIDUO_HUMAN,MIEF1 upstream open reading frame protein (Alt...,MIEF1,Homo sapiens (Human),70.0,cellular response to hypoxia [GO:0071456]; pos...,mitochondrial matrix [GO:0005759]; mitochondri...,GO:0005739; GO:0005759; GO:0042254; GO:0070131...,mitochondrial matrix [GO:0005759]; mitochondri...,NaN,MIEF1,NaN,x
99,Q9NQG6,Q9NQG6,reviewed,MID51_HUMAN,Mitochondrial dynamics protein MID51 (Mitochon...,MIEF1 MID51 SMCR7L,Homo sapiens (Human),463.0,cellular response to hypoxia [GO:0071456]; mit...,integral component of membrane [GO:0016021]; m...,GO:0000266; GO:0005739; GO:0005741; GO:0016021...,integral component of membrane [GO:0016021]; m...,ADP binding [GO:0043531]; GDP binding [GO:0019...,MIEF1,NaN,x
100,Q9NQG6,Q9NQG6,reviewed,MID51_HUMAN,Mitochondrial dynamics protein MID51 (Mitochon...,MIEF1 MID51 SMCR7L,Homo sapiens (Human),463.0,cellular response to hypoxia [GO:0071456]; mit...,integral component of membrane [GO:0016021]; m...,GO:0000266; GO:0005739; GO:0005741; GO:0016021...,integral component of membrane [GO:0016021]; m...,ADP binding [GO:0043531]; GDP binding [GO:0019...,MIEF1,NaN,x
336,P0DP91,P0DP91,reviewed,ERPG3_HUMAN,Chimeric ERCC6-PGBD3 protein (Chimeric CSB-PGB...,ERCC6,Homo sapiens (Human),1061.0,positive regulation of defense response to vir...,nuclear body [GO:0016604]; nucleoplasm [GO:000...,GO:0002230; GO:0005654; GO:0010628; GO:0016604...,nuclear body [GO:0016604]; nucleoplasm [GO:000...,sequence-specific DNA binding [GO:0043565],ERCC6,NaN,x
337,P0DP91,P0DP91,reviewed,ERPG3_HUMAN,Chimeric ERCC6-PGBD3 protein (Chimeric CSB-PGB...,ERCC6,Homo sapiens (Human),1061.0,positive regulation of defense response to vir...,nuclear body [GO:0016604]; nucleoplasm [GO:000...,GO:0002230; GO:0005654; GO:0010628; GO:0016604...,nuclear body [GO:0016604]; nucleoplasm [GO:000...,sequence-specific DNA binding [GO:0043565],ERCC6,NaN,x
338,Q03468,Q03468,reviewed,ERCC6_HUMAN,"DNA excision repair protein ERCC-6, EC 3.6.4.-...",ERCC6 CSB,Homo sapiens (Human),1493.0,base-excision repair [GO:0006284]; chromatin r...,B-WICH complex [GO:0110016]; nucleolus [GO:000...,GO:0000012; GO:0000077; GO:0000303; GO:0003677...,B-WICH complex [GO:0110016]; nucleolus [GO:000...,ATP binding [GO:0005524]; ATP hydrolysis activ...,ERCC6,NaN,x
339,Q03468,Q03468,reviewed,ERCC6_HUMAN,"DNA excision repair protein ERCC-6, EC 3.6.4.-...",ERCC6 CSB,Homo sapiens (Human),1493.0,base-excision repair [GO:0006284]; chromatin r...,B-WICH complex [GO:0110016]; nucleolus [GO:000...,GO:0000012; GO:0000077; GO:0000303; GO:0003677...,B-WICH complex [GO:0110016]; nucleolus [GO:000...,ATP binding [GO:0005524]; ATP hydrolysis activ...,ERCC6,NaN,x
340,P0DPQ6,P0DPQ6,reviewed,DT3UO_HUMAN,DDIT3 upstream open reading frame protein (Alt...,DDIT3,Homo sapiens (Human),34.0,NaN,cytoplasm [GO:0005737]; nucleus [GO:0005634],GO:0005634; GO:0005737,cytoplasm [GO:0005737]; nucleus [GO:0005634],NaN,DDIT3,NaN,x
341,P0DPQ6,P0DPQ6,reviewed,DT3UO_HUMAN,DDIT3 upstream open reading frame protein (Alt...,DDIT3,Homo sapiens (Human),34.0,NaN,cytoplasm [GO:0005737]; nucleus [GO:0005634],GO:0005634; GO:0005737,cytoplasm [GO:0005737]; nucleus [GO:0005634],NaN,DDIT3,NaN,x
342,P35638,P35638,reviewed,DDIT3_HUMAN,"DNA damage-inducible transcript 3 protein, DDI...",DDIT3 CHOP CHOP10 GADD153,Homo sapiens (Human),169.0,anterior/posterior axis specification [GO:0009...,CHOP-ATF3 complex [GO:1990622]; CHOP-ATF4 comp...,GO:0000122; GO:0000785; GO:0000976; GO:0000978...,CHOP-ATF3 complex [GO:1990622]; CHOP-ATF4 comp...,cAMP response element binding protein binding ...,DDIT3,NaN,x
343,P35638,P35638,reviewed,DDIT3_HUMAN,"DNA damage-inducible transcript 3 protein, DDI...",DDIT3 CHOP CHOP10 GADD153,Homo sapiens (Human),169.0,anterior/posterior axis specification [GO:0009...,CHOP-ATF3 complex [GO:1990622]; CHOP-ATF4 comp...,GO:0000122; GO:0000785; GO:0000976; GO:0000978...,CHOP-ATF3 complex [GO:1990622]; CHOP-ATF4 comp...,cAMP response element binding protein binding ...,DDIT3,NaN,x
538,P39880,P39880,reviewed,CUX1_HUMAN,Homeobox protein cut-like 1 (CCAAT displacemen...,CUX1 CUTL1,Homo sapiens (Human),1505.0,negative regulation of transcription by RNA po...,chromatin [GO:0000785]; cytosol [GO:0005829]; ...,GO:0000122; GO:0000785; GO:0000977; GO:0000981...,chromatin [GO:0000785]; cytosol [GO:0005829]; ...,"DNA-binding transcription factor activity, RNA...",CUX1,NaN,x
539,P39880,P39880,reviewed,CUX1_HUMAN,Homeobox protein cut-like 1 (CCAAT displacemen...,CUX1 CUTL1,Homo sapiens (Human),1505.0,negative regulation of transcription by RNA po...,chromatin [GO:0000785]; cytosol [GO:0005829]; ...,GO:0000122; GO:0000785; GO:0000977; GO:0000981...,chromatin [GO:0000785]; cytosol [GO:0005829]; ...,"DNA-binding transcription factor activity, RNA...",CUX1,NaN,x
540,Q13948,Q13948,reviewed,CASP_HUMAN,Protein CASP,CUX1 CUTL1,Homo sapiens (Human),678.0,intra-Golgi vesicle-mediated transport [GO:000...,Golgi apparatus [GO:0005794]; Golgi membrane [...,GO:0000139; GO:0005654; GO:0005794; GO:0006891...,Golgi apparatus [GO:0005794]; Golgi membrane [...,NaN,CUX1,NaN,x
541,Q13948,Q13948,reviewed,CASP_HUMAN,Protein CASP,CUX1 CUTL1,Homo sapiens (Human),678.0,intra-Golgi vesicle-mediated transport [GO:000...,Golgi apparatus [GO:0005794]; Golgi membrane [...,GO:0000139; GO:0005654; GO:0005794; GO:0006891...,Golgi apparatus [GO:0005794]; Golgi membrane [...,NaN,CUX1,NaN,x
845,Q13888,Q13888,reviewed,TF2H2_HUMAN,General transcription factor IIH subunit 2 (Ba...,GTF2H2 BTF2P44,Homo sapiens (Human),395.0,G protein-coupled receptor internalization [GO...,core TFIIH complex portion of holo TFIIH compl...,GO:0000438; GO:0000439; GO:0002031; GO:0005634...,core TFIIH complex portion of holo TFIIH compl...,protein N-terminus binding [GO:0047485]; RNA p...,GTF2H2,NaN,x
846,Q13888,Q13888,reviewed,TF2H2_HUMAN,General transcription factor IIH subunit 2 (Ba...,GTF2H2 BTF2P44,Homo sapiens (Human),395.0,G protein-coupled receptor internalization [GO...,core TFIIH complex portion of holo TFIIH compl...,GO:0000438; GO:0000439; GO:0002031; GO:0005634...,core TFIIH complex portion of holo TFIIH compl...,protein N-terminus binding [GO:0047485]; RNA p...,GTF2H2,NaN,x

In [110]:
new_uniprot_table

,From,Entry,Reviewed,Entry Name,Protein names,Gene Names,Organism,Length,Gene Ontology (biological process),Gene Ontology (GO),Gene Ontology IDs,Gene Ontology (cellular component),Gene Ontology (molecular function),"TFs (GSEA, 2022)",NOTE,placeholder
0,A6NDR6,A6NDR6,reviewed,ME3L1_HUMAN,Putative homeobox protein Meis3-like 1,MEIS3P1,Homo sapiens (Human),274.0,animal organ morphogenesis [GO:0009887]; brain...,nucleus [GO:0005634]; DNA-binding transcriptio...,GO:0000978; GO:0000981; GO:0001228; GO:0001654...,nucleus [GO:0005634],"DNA-binding transcription activator activity, ...",MEIS3P1,manual check: found,x
1,A8K0S8,A8K0S8,reviewed,ME3L2_HUMAN,Putative homeobox protein Meis3-like 2,MEIS3P2,Homo sapiens (Human),358.0,animal organ morphogenesis [GO:0009887]; brain...,nucleus [GO:0005634]; DNA-binding transcriptio...,GO:0000978; GO:0000981; GO:0001228; GO:0001654...,nucleus [GO:0005634],"DNA-binding transcription activator activity, ...",MEIS3P2,manual check: found,x
2,P0C5K6,P0C5K6,reviewed,CT18_HUMAN,Putative tumor antigen NA88-A (Cancer/testis a...,VENTXP1,Homo sapiens (Human),33.0,NaN,NaN,NaN,NaN,NaN,VENTXP1,manual check: found,x
3,P12525,P12525,reviewed,MYCP1_HUMAN,Putative myc-like protein MYCLP1 (Protein L-My...,MYCLP1 MYCL1P1 MYCL2,Homo sapiens (Human),358.0,regulation of transcription by RNA polymerase ...,nucleus [GO:0005634]; DNA binding [GO:0003677]...,GO:0000981; GO:0003677; GO:0003700; GO:0005634...,nucleus [GO:0005634],DNA binding [GO:0003677]; DNA-binding transcri...,MYCLP1,manual check: found,x
4,P40205,P40205,reviewed,NCYM_HUMAN,N-cym protein (N-myc opposite strand),MYCNOS CYMN NCYM,Homo sapiens (Human),109.0,negative regulation of kinase activity [GO:003...,cytoplasm [GO:0005737]; nucleus [GO:0005634]; ...,GO:0005634; GO:0005737; GO:0031647; GO:0033673,cytoplasm [GO:0005737]; nucleus [GO:0005634],NaN,MYCNOS,manual check: found,x
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1545,Q9Y6Q3,Q9Y6Q3,reviewed,ZFP37_HUMAN,"Zinc finger protein 37 homolog, Zfp-37",ZFP37,Homo sapiens (Human),630.0,negative regulation of transcription by RNA po...,nucleus [GO:0005634]; DNA-binding transcriptio...,GO:0000122; GO:0000977; GO:0000981; GO:0001227...,nucleus [GO:0005634],DNA-binding transcription factor activity [GO:...,ZFP37,NaN,x
1546,Q9Y6Q9,Q9Y6Q9,reviewed,NCOA3_HUMAN,"Nuclear receptor coactivator 3, NCoA-3, EC 2.3...",NCOA3 AIB1 BHLHE42 RAC3 TRAM1,Homo sapiens (Human),1424.0,cell dedifferentiation [GO:0043697]; cellular ...,chromatin [GO:0000785]; cytoplasm [GO:0005737]...,GO:0000785; GO:0000993; GO:0003713; GO:0004402...,chromatin [GO:0000785]; cytoplasm [GO:0005737]...,disordered domain specific binding [GO:0097718...,NCOA3,NaN,x
1547,Q9Y6X0,Q9Y6X0,reviewed,SETBP_HUMAN,"SET-binding protein, SEB",SETBP1 KIAA0437,Homo sapiens (Human),1596.0,histone H3-K36 dimethylation [GO:0097676]; his...,cytosol [GO:0005829]; nuclear body [GO:0016604...,GO:0003677; GO:0005654; GO:0005829; GO:0006355...,cytosol [GO:0005829]; nuclear body [GO:0016604...,DNA binding [GO:0003677]; histone methyltransf...,SETBP1,NaN,x
1548,Q9Y6X2,Q9Y6X2,reviewed,PIAS3_HUMAN,"E3 SUMO-protein ligase PIAS3, EC 2.3.2.- (E3 S...",PIAS3,Homo sapiens (Human),628.0,negative regulation of gene expression [GO:001...,cytoplasm [GO:0005737]; dendrite [GO:0030425];...,GO:0000122; GO:0003712; GO:0005654; GO:0005737...,cytoplasm [GO:0005737]; dendrite [GO:0030425];...,enzyme binding [GO:0019899]; potassium channel...,PIAS3,NaN,x
1549,Q9Y6X8,Q9Y6X8,reviewed,ZHX2_HUMAN,Zinc fingers and homeoboxes protein 2 (Alpha-f...,ZHX2 AFR1 KIAA0854 RAF,Homo sapiens (Human),837.0,mRNA catabolic process [GO:0006402]; negative ...,chromatin [GO:0000785]; cytosol [GO:0005829]; ...,GO:0000122; GO:0000785; GO:0000981; GO:0003677...,chromatin [GO:0000785]; cytosol [GO:0005829]; ...,DNA binding [GO:0003677]; DNA-binding transcri...,ZHX2,NaN,x

In [112]:
new_uniprot_table[new_uniprot_table["TFs (GSEA, 2022)"].duplicated(keep=False)]

,From,Entry,Reviewed,Entry Name,Protein names,Gene Names,Organism,Length,Gene Ontology (biological process),Gene Ontology (GO),Gene Ontology IDs,Gene Ontology (cellular component),Gene Ontology (molecular function),"TFs (GSEA, 2022)",NOTE,placeholder
97,L0R8F8,L0R8F8,reviewed,MIDUO_HUMAN,MIEF1 upstream open reading frame protein (Alt...,MIEF1,Homo sapiens (Human),70.0,cellular response to hypoxia [GO:0071456]; pos...,mitochondrial matrix [GO:0005759]; mitochondri...,GO:0005739; GO:0005759; GO:0042254; GO:0070131...,mitochondrial matrix [GO:0005759]; mitochondri...,NaN,MIEF1,NaN,x
99,Q9NQG6,Q9NQG6,reviewed,MID51_HUMAN,Mitochondrial dynamics protein MID51 (Mitochon...,MIEF1 MID51 SMCR7L,Homo sapiens (Human),463.0,cellular response to hypoxia [GO:0071456]; mit...,integral component of membrane [GO:0016021]; m...,GO:0000266; GO:0005739; GO:0005741; GO:0016021...,integral component of membrane [GO:0016021]; m...,ADP binding [GO:0043531]; GDP binding [GO:0019...,MIEF1,NaN,x
336,P0DP91,P0DP91,reviewed,ERPG3_HUMAN,Chimeric ERCC6-PGBD3 protein (Chimeric CSB-PGB...,ERCC6,Homo sapiens (Human),1061.0,positive regulation of defense response to vir...,nuclear body [GO:0016604]; nucleoplasm [GO:000...,GO:0002230; GO:0005654; GO:0010628; GO:0016604...,nuclear body [GO:0016604]; nucleoplasm [GO:000...,sequence-specific DNA binding [GO:0043565],ERCC6,NaN,x
338,Q03468,Q03468,reviewed,ERCC6_HUMAN,"DNA excision repair protein ERCC-6, EC 3.6.4.-...",ERCC6 CSB,Homo sapiens (Human),1493.0,base-excision repair [GO:0006284]; chromatin r...,B-WICH complex [GO:0110016]; nucleolus [GO:000...,GO:0000012; GO:0000077; GO:0000303; GO:0003677...,B-WICH complex [GO:0110016]; nucleolus [GO:000...,ATP binding [GO:0005524]; ATP hydrolysis activ...,ERCC6,NaN,x
340,P0DPQ6,P0DPQ6,reviewed,DT3UO_HUMAN,DDIT3 upstream open reading frame protein (Alt...,DDIT3,Homo sapiens (Human),34.0,NaN,cytoplasm [GO:0005737]; nucleus [GO:0005634],GO:0005634; GO:0005737,cytoplasm [GO:0005737]; nucleus [GO:0005634],NaN,DDIT3,NaN,x
342,P35638,P35638,reviewed,DDIT3_HUMAN,"DNA damage-inducible transcript 3 protein, DDI...",DDIT3 CHOP CHOP10 GADD153,Homo sapiens (Human),169.0,anterior/posterior axis specification [GO:0009...,CHOP-ATF3 complex [GO:1990622]; CHOP-ATF4 comp...,GO:0000122; GO:0000785; GO:0000976; GO:0000978...,CHOP-ATF3 complex [GO:1990622]; CHOP-ATF4 comp...,cAMP response element binding protein binding ...,DDIT3,NaN,x
538,P39880,P39880,reviewed,CUX1_HUMAN,Homeobox protein cut-like 1 (CCAAT displacemen...,CUX1 CUTL1,Homo sapiens (Human),1505.0,negative regulation of transcription by RNA po...,chromatin [GO:0000785]; cytosol [GO:0005829]; ...,GO:0000122; GO:0000785; GO:0000977; GO:0000981...,chromatin [GO:0000785]; cytosol [GO:0005829]; ...,"DNA-binding transcription factor activity, RNA...",CUX1,NaN,x
540,Q13948,Q13948,reviewed,CASP_HUMAN,Protein CASP,CUX1 CUTL1,Homo sapiens (Human),678.0,intra-Golgi vesicle-mediated transport [GO:000...,Golgi apparatus [GO:0005794]; Golgi membrane [...,GO:0000139; GO:0005654; GO:0005794; GO:0006891...,Golgi apparatus [GO:0005794]; Golgi membrane [...,NaN,CUX1,NaN,x

In [165]:
remove_dubli_df = pd.read_csv("uniprot_mapping_human_remove_duplicates.csv")
remove_dubli_df.shape

(1550, 15)

In [167]:
remove_dubli_df.drop_duplicates()

,From,Entry,Reviewed,Entry Name,Protein names,Gene Names,Organism,Length,Gene Ontology (biological process),Gene Ontology (GO),Gene Ontology IDs,Gene Ontology (cellular component),Gene Ontology (molecular function),"TFs (GSEA, 2022)",NOTE
0,A6NDR6,A6NDR6,reviewed,ME3L1_HUMAN,Putative homeobox protein Meis3-like 1,MEIS3P1,Homo sapiens (Human),274.0,animal organ morphogenesis [GO:0009887]; brain...,nucleus [GO:0005634]; DNA-binding transcriptio...,GO:0000978; GO:0000981; GO:0001228; GO:0001654...,nucleus [GO:0005634],"DNA-binding transcription activator activity, ...",MEIS3P1,manual check: found
1,A8K0S8,A8K0S8,reviewed,ME3L2_HUMAN,Putative homeobox protein Meis3-like 2,MEIS3P2,Homo sapiens (Human),358.0,animal organ morphogenesis [GO:0009887]; brain...,nucleus [GO:0005634]; DNA-binding transcriptio...,GO:0000978; GO:0000981; GO:0001228; GO:0001654...,nucleus [GO:0005634],"DNA-binding transcription activator activity, ...",MEIS3P2,manual check: found
2,P0C5K6,P0C5K6,reviewed,CT18_HUMAN,Putative tumor antigen NA88-A (Cancer/testis a...,VENTXP1,Homo sapiens (Human),33.0,NaN,NaN,NaN,NaN,NaN,VENTXP1,manual check: found
3,P12525,P12525,reviewed,MYCP1_HUMAN,Putative myc-like protein MYCLP1 (Protein L-My...,MYCLP1 MYCL1P1 MYCL2,Homo sapiens (Human),358.0,regulation of transcription by RNA polymerase ...,nucleus [GO:0005634]; DNA binding [GO:0003677]...,GO:0000981; GO:0003677; GO:0003700; GO:0005634...,nucleus [GO:0005634],DNA binding [GO:0003677]; DNA-binding transcri...,MYCLP1,manual check: found
4,P40205,P40205,reviewed,NCYM_HUMAN,N-cym protein (N-myc opposite strand),MYCNOS CYMN NCYM,Homo sapiens (Human),109.0,negative regulation of kinase activity [GO:003...,cytoplasm [GO:0005737]; nucleus [GO:0005634]; ...,GO:0005634; GO:0005737; GO:0031647; GO:0033673,cytoplasm [GO:0005737]; nucleus [GO:0005634],NaN,MYCNOS,manual check: found
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1545,Q9Y6Q3,Q9Y6Q3,reviewed,ZFP37_HUMAN,"Zinc finger protein 37 homolog, Zfp-37",ZFP37,Homo sapiens (Human),630.0,negative regulation of transcription by RNA po...,nucleus [GO:0005634]; DNA-binding transcriptio...,GO:0000122; GO:0000977; GO:0000981; GO:0001227...,nucleus [GO:0005634],DNA-binding transcription factor activity [GO:...,ZFP37,NaN
1546,Q9Y6Q9,Q9Y6Q9,reviewed,NCOA3_HUMAN,"Nuclear receptor coactivator 3, NCoA-3, EC 2.3...",NCOA3 AIB1 BHLHE42 RAC3 TRAM1,Homo sapiens (Human),1424.0,cell dedifferentiation [GO:0043697]; cellular ...,chromatin [GO:0000785]; cytoplasm [GO:0005737]...,GO:0000785; GO:0000993; GO:0003713; GO:0004402...,chromatin [GO:0000785]; cytoplasm [GO:0005737]...,disordered domain specific binding [GO:0097718...,NCOA3,NaN
1547,Q9Y6X0,Q9Y6X0,reviewed,SETBP_HUMAN,"SET-binding protein, SEB",SETBP1 KIAA0437,Homo sapiens (Human),1596.0,histone H3-K36 dimethylation [GO:0097676]; his...,cytosol [GO:0005829]; nuclear body [GO:0016604...,GO:0003677; GO:0005654; GO:0005829; GO:0006355...,cytosol [GO:0005829]; nuclear body [GO:0016604...,DNA binding [GO:0003677]; histone methyltransf...,SETBP1,NaN
1548,Q9Y6X2,Q9Y6X2,reviewed,PIAS3_HUMAN,"E3 SUMO-protein ligase PIAS3, EC 2.3.2.- (E3 S...",PIAS3,Homo sapiens (Human),628.0,negative regulation of gene expression [GO:001...,cytoplasm [GO:0005737]; dendrite [GO:0030425];...,GO:0000122; GO:0003712; GO:0005654; GO:0005737...,cytoplasm [GO:0005737]; dendrite [GO:0030425];...,enzyme binding [GO:0019899]; potassium channel...,PIAS3,NaN
1549,Q9Y6X8,Q9Y6X8,reviewed,ZHX2_HUMAN,Zinc fingers and homeoboxes protein 2 (Alpha-f...,ZHX2 AFR1 KIAA0854 RAF,Homo sapiens (Human),837.0,mRNA catabolic process [GO:0006402]; negative ...,chromatin [GO:0000785]; cytosol [GO:0005829]; ...,GO:0000122; GO:0000785; GO:0000981; GO:0003677...,chromatin [GO:0000785]; cytosol [GO:0005829]; ...,DNA binding [GO:0003677]; DNA-binding transcri...,ZHX2,NaN

In [171]:
fina_csv = pd.read_csv("human_uniprot_mapping.csv")
fina_csv.shape

(1550, 15)

In [172]:
fina_csv = fina_csv.drop_duplicates()
fina_csv.shape

(1541, 15)

In [173]:
fina_csv.to_csv("human_uniprot_mapping.csv")